modLoader="javafml"
loaderVersion="[45,)"
issueTrackerURL="https://github.com/r8420/MoreOverlays-updated/issues"
license="The MIT License (MIT)"
[[mods]]
	modId="moreoverlays"
	version="${file.jarVersion}"
	displayName="More Overlays Updated"
# 	updateJSONURL="https://raw.githubusercontent.com/feldim2425/Mod_Update-JSONs/master/MoreOverlays.json"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/more-overlays-updated"
	logoFile="moreoverlays.png"
	credits="Thanks to all contributors of this project"
	authors="feldim2425, RiDGo8/R8420"
	displayTest="IGNORE_ALL_VERSION"
    description='''
    Adds some overlays from the old (MC 1.7.x) NotEnoughItems Mod:
    * Chunk and Region borders
    * Mob spawn / Light overlay
    * Item search when JEI (JustEnoughItems by Mezz) is installed
    '''

[[dependencies.moreoverlays]]
    modId="forge"
    mandatory=true 
    versionRange="[41.0.94,)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.moreoverlays]]
    modId="jei"
    mandatory=false
    versionRange="[6.0.0.25,)"
    ordering="NONE"
    side="CLIENT"
